#!/bin/bash

set -o errexit

[[ ${DEBUG} == true ]] && set -x

source /opt/volumerize/base.sh

DUPLICITY_RETURN_CODE=0

function restore() {
  ${DUPLICITY_COMMAND} restore --force $@ ${DUPLICITY_OPTIONS} ${VOLUMERIZE_INCUDES} ${VOLUMERIZE_TARGET} ${VOLUMERIZE_SOURCE} || DUPLICITY_RETURN_CODE=$? && true ;
}

${VOLUMERIZE_SCRIPT_DIR}/prepoststrategy preAction restore
source ${VOLUMERIZE_SCRIPT_DIR}/stopContainers.sh
restore $@
source ${VOLUMERIZE_SCRIPT_DIR}/startContainers.sh
${VOLUMERIZE_SCRIPT_DIR}/prepoststrategy postAction restore
exit $DUPLICITY_RETURN_CODE
