#!/bin/bash

set -o errexit

[[ ${DEBUG} == true ]] && set -x

source /opt/volumerize/base.sh

DUPLICITY_RETURN_CODE=0

function commandLoop() {
  local jobcount=$JOB_COUNT
  local counter;

  for (( counter=1; counter<=$jobcount; counter++ ))
  do
    commandJob "$counter" $@
  done
}

function commandJob() {
  local jobNumber=$1
  local returnCode=0;
  prepareJob "$jobNumber"
  shift;
  ${DUPLICITY_JOB_COMMAND} restore --force $@ ${DUPLICITY_JOB_OPTIONS} ${VOLUMERIZE_JOB_INCLUDES} ${VOLUMERIZE_JOB_TARGET} ${VOLUMERIZE_JOB_SOURCE} || returnCode=$? && true ;
  if [ "$returnCode" -gt "$DUPLICITY_RETURN_CODE" ]; then
    DUPLICITY_RETURN_CODE=$returnCode
  fi
}

function commandExecution() {
  if [ -n "${VOLUMERIZE_SOURCE}" ]; then
    ${DUPLICITY_COMMAND} restore --force $@ ${DUPLICITY_OPTIONS} ${VOLUMERIZE_INCLUDES} ${VOLUMERIZE_TARGET} ${VOLUMERIZE_SOURCE} || DUPLICITY_RETURN_CODE=$? && true ;
  elif [ ! -z "${1##*[!0-9]*}" ]; then
    commandJob $@
  elif [ -n "${JOB_COUNT}" ]; then
    commandLoop $@
  fi
}

${VOLUMERIZE_SCRIPT_DIR}/prepoststrategy preAction restore
source ${VOLUMERIZE_SCRIPT_DIR}/stopContainers.sh
commandExecution $@
source ${VOLUMERIZE_SCRIPT_DIR}/startContainers.sh
export DUPLICITY_RETURN_CODE
${VOLUMERIZE_SCRIPT_DIR}/prepoststrategy postAction restore
exit $DUPLICITY_RETURN_CODE
